# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-18T09:38:32Z"
  labels:
    app: stock-service
  name: stock-service
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    command:
    - /docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PKG_RELEASE
      value: "2"
    - name: NGINX_VERSION
      value: 1.18.0
    - name: NJS_VERSION
      value: 0.4.4
    image: localhost/stock-ui:dev
    name: stock-ui
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: TCP
    - containerPort: 80
      hostPort: 9000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    workingDir: /
  - command:
    - java
    - -jar
    - /app.jar
    env:
    - name: PATH
      value: /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: JAVA_VERSION
      value: jdk-11.0.10+9
    - name: JAVA_HOME
      value: /opt/java/openjdk
    - name: LANG
      value: en_US.UTF-8
    - name: LANGUAGE
      value: en_US:en
    - name: LC_ALL
      value: en_US.UTF-8
    image: localhost/stock-api:dev
    name: stock-api
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    workingDir: /
  dnsConfig: {}
  restartPolicy: Never
status: {}
